### ISSUE TITLE
Graylog does not process messages with empty `msg`

### ISSUE THREAD

**Issue by rhduwe** [mhart/gelf-stream#13]
This works as expected:

```
log.info("message");
log.info({object: object}, "message");
```

But those get marked in graylog as "incomplete", while still being written normally to other streams:

```
log.info({"test":"test"});
log.info(config);
log.info("");
```

**Comment by FBerthelot** [comment]
@mhart I have the same issue.

I think the problem came from you gelfling module, but I'm not sure

**Comment by mhart** [comment]
@rhduwe @FBerthelot well `msg` is a required field for Bunyan if you're using record objects: https://github.com/trentm/node-bunyan#core-fields

I'm going to close this as the bunyan mapper expects the input to be a valid bunyan record.

**Comment by FBerthelot** [comment]
To me the only problem here is when you are calling :
```javascript
log.info({"test":"test"});
```
The `msg` is not empty at all, but your are considering it like an empty message.

**Comment by mhart** [comment]
@FBerthelot Not sure what you mean? `msg` is absolutely empty in your example – the only property you've got there is `test`. If you're sending objects to Bunyan, you need to have a `msg` property

**Comment by FBerthelot** [comment]
@mhart nevermind, I was totaly wrong.

I believed that `msg` was the english shortcut for `message` and refer to the first param of the logging function... 

For your information, we use your plugin for [a famous french news website](www.lci.fr) and it work like a charm now ;)

Thank you
