### ISSUE TITLE
name is not defined

### ISSUE THREAD

**Issue by akonsu** [mhart/gelf-stream#8]
this line references `cb` which seems to be undefined: https://github.com/mhart/gelf-stream/blob/e531719e34248ca6079e4988b35b1ec49fdeba7a/gelf-stream.js#L34

cc: @milas

**Comment by mhart** [comment]
Oh, nice pickup. Yeah, introduced here I think: https://github.com/mhart/gelf-stream/commit/ea6929c7a087dae2098d3e8fe05ec774887b1368

**Comment by mhart** [comment]
Fixed in v1.0.1 – thanks for the heads up!
